print("Welcome to the Band Name Generator")
userCity =input("What's the name of the city you grew up?")
print(userCity)
userPet = input("What's your pet's name?")
print(userPet)
print("Your band name could be " + userCity + " " + userPet)
